### ISSUE TITLE
[Bug report] Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by xdewx** [Tencent/cherry-markdown#401]
**Describe the bug**
调用setMarkdown后，在编辑框内无法继续输入，控制台提示：
```js
cherry-markdown.core.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at kn2 (cherry-markdown.core.js:1:77288)
    at Ln2 (cherry-markdown.core.js:1:78003)
    at jn2 (cherry-markdown.core.js:1:82781)
    at vr2 (cherry-markdown.core.js:1:89638)
    at mr2 (cherry-markdown.core.js:1:89575)
    at Vo2.prepareSelection (cherry-markdown.core.js:1:192796)
    at zr2 (cherry-markdown.core.js:1:103088)
    at cherry-markdown.core.js:1:101808
    at cherry-markdown.core.js:1:101888
    at cherry-markdown.core.js:1:101612
```

另外可以观察到的是：
1. setMarkdown后游标的位置和文本位置不一致，如图
![image](https://user-images.githubusercontent.com/20438962/222678583-b7a59777-7af6-450d-acd4-ccf38fbf5adb.png)

**To Reproduce**
1. init
3. setMarkdown

**Expected behavior**
在setMarkdown后可以继续正常输入

**Environment (please complete the following information):**
 - OS: linux
 - Browser : edge
 - Version：0.8.14

**Comment by xdewx** [comment]
![image](https://user-images.githubusercontent.com/20438962/222886683-6db8f387-6109-4694-8462-0d54cb9310a9.png)
从这里找到了解决方式
