### ISSUE TITLE
[Bug report] `toolbarRight`   can not custom menu

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#527]
The error is as follows:
```
Toolbar.js:131 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createBtn')
    at Toolbar.js:131:42
    at Array.forEach (<anonymous>)
    at Toolbar.drawRightMenus (Toolbar.js:130:5)
    at Toolbar.drawMenus (Toolbar.js:111:51)
    at new Toolbar (Toolbar.js:47:10)
    at Cherry.createToolbar (Cherry.js:391:20)
    at Cherry.init (Cherry.js:136:25)
    at new Cherry (Cherry.js:98:10)
    at index-demo.js:209:19
（匿名） @ Toolbar.js:131
drawRightMenus @ Toolbar.js:130
drawMenus @ Toolbar.js:111
Toolbar @ Toolbar.js:47
createToolbar @ Cherry.js:391
init @ Cherry.js:136
Cherry @ Cherry.js:98
（匿名） @ index-demo.js:209
Promise.then（异步）
（匿名） @ index-demo.js:207
contentScript.bundle.js:67 Unique user id has not been set in posthog.identify
```

**Comment by RSS1102** [comment]
When multiple ` Level2Menu` appear, clicking on a non first ` Level2Menu` brings up the first secondary menu.
![image](https://github.com/Tencent/cherry-markdown/assets/81673017/83dc8bb7-6176-4729-baf9-37c9e117816b)

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/pull/531
改了一版，求
