### ISSUE TITLE
[Bug Report] 点击预览区图片会报错

### ISSUE THREAD

**Issue by xiaopya** [Tencent/cherry-markdown#909]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

umi.ts:25 [Mako] Runtime error found, and it will cause a full reload. If you want HMR to work, please fix the error. 
ErrorEvent {isTrusted: true, message: "Uncaught TypeError: Cannot read properties of null (reading '0')"}
cherry-markdown.core.js:1 Uncaught TypeError: Cannot read properties of null (reading '0')
    at e.value (cherry-markdown.core.js:1:1132898)
    at e.value (cherry-markdown.core.js:1:1131287)
    at e.value (cherry-markdown.core.js:1:1128916)

### Contributing

None

**Comment by RSS1102** [comment]
能否提供更加详细的复现步骤/复现代码，或者视频，
